### ISSUE TITLE
Is this situation right when open the html file like this?

### ISSUE THREAD

**Issue by litxiaoyao** [bhowmickanusha/MusicVisualisationUsingEmotionRecognition#1]
![image](https://user-images.githubusercontent.com/68361174/190888105-bba79fa0-fa28-4d57-9399-5d9964534c3b.png)

So how would I do to choose my song file?

**Comment by bhowmickanusha** [comment]
Apologies, the wrong file was uploaded. I've uploaded the correct html file (songchoicepage.html)
